// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIApp.Data;

namespace WebAPIApp.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20200418155414_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIApp.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Auteur");

                    b.Property<string>("Texte");

                    b.Property<string>("Titre");

                    b.Property<int?>("blogId");

                    b.HasKey("Id");

                    b.HasIndex("blogId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WebAPIApp.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categorie");

                    b.Property<string>("SousTitre");

                    b.Property<string>("Titre");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("WebAPIApp.Models.Article", b =>
                {
                    b.HasOne("WebAPIApp.Models.Blog", "blog")
                        .WithMany()
                        .HasForeignKey("blogId");
                });
#pragma warning restore 612, 618
        }
    }
}
